name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: explainer/index.html
          DESTINATION: explainer/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: gap-analysis_and_use-case/index.html
          DESTINATION: gap-analysis_and_use-case/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: technical-approach/index.html
          DESTINATION: technical-approach/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: user-scenarios/index.html
          DESTINATION: user-scenarios/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: sample/index.html
          DESTINATION: sample/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
      
